services:
  postgres-01:
    image: postgres:18-alpine
    restart: unless-stopped
    container_name: postgres_01
    environment:
      - POSTGRES_PASSWORD=${TF_VAR_pwd_postgres_01}
    ports:
      - "5432:5432"
    networks:
      - postgres_01
      - openbao
    volumes:
      - postgres_01:/var/lib/postgresql
    command: ["postgres", "-c", "max_connections=250"]

  postgres-02:
    image: postgres:18-alpine
    restart: unless-stopped
    container_name: postgres_02
    environment:
      - POSTGRES_PASSWORD=${TF_VAR_pwd_postgres_02}
    networks:
      - postgres_02
      - openbao
    ports:
      - "5433:5432"
    volumes:
      - postgres_02:/var/lib/postgresql
    command: ["postgres", "-c", "max_connections=250"]

  redis_01:
    image: redis:8-alpine  
    container_name: redis-cache-01
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_01:/data
    command: redis-server --requirepass ${REDIS_PASSWORD} --appendonly yes
    networks:
      - redis_01
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "${REDIS_PASSWORD}", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3

networks:
  postgres_01:
    external: true
    name: postgres_02
  postgres_02:
    external: true
    name: postgres_02
  openbao:
    external: true
    name: openbao
  redis_01:
    external: true
    name: redis_01

volumes:
  postgres_01:
    external: true
  postgres_02:
    external: true
  redis_01:
    external: true
