# docker exec nginx-reverse-proxy nginx -s reload
services:
  nginx-proxy:
    image: nginx:alpine
    container_name: nginx-reverse-proxy
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./sites-enabled:/etc/nginx/sites-enabled:ro
    networks:
      - nginx_reverse_proxy
    restart: always

networks:
  nginx_reverse_proxy:
    external: true
    name: nginx_reverse_proxy
