name: Nginx Docker Container

on:
  push:
    branches:
      - 'main'
    paths:
      - 'nginx/docker-compose.yaml'
      - '.github/workflows/nginx-docker.yaml'
  workflow_dispatch:


jobs:
  bring-up-nginx:
    runs-on: [self-hosted, Windows, X64]  # Targets your self-hosted runner pool
    defaults:
      run:
        shell: powershell -ExecutionPolicy Bypass {0}

    steps:
      # Clone only the specific path from that branch (Sparse Checkout)
      - name: Checkout specific path
        uses: actions/checkout@v4
        with:
          ref: 'main'
          sparse-checkout: |
            nginx
          sparse-checkout-cone-mode: true

      # Run your Windows command inside the target folder
      - name: Run command in path
        working-directory: .\nginx
        env:
          TF_VAR_pwd_postgres_01: ${{ secrets.TF_VAR_PWD_POSTGRES_01 }}
          TF_VAR_pwd_postgres_02: ${{ secrets.TF_VAR_PWD_POSTGRES_02 }}
        run: |
          Write-Output "Currently running in: $(Get-Location)"
          docker compose -p nginx up -d
          docker compose exec nginx-proxy nginx -s reload
      - name: Post-run workspace cleanup
        if: always()
        run: |
          Write-Output "Cleaning up self-hosted workspace..."
          Remove-Item -Path * -Recurse -Force -ErrorAction SilentlyContinue
